### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by biranchi2018** [keithrozario/Klayers#79] opened 2020-01-07 02:09 UTC
**Describe the bug**

I am getting the following error:

{
    "errorMessage": "[E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.",
    "errorType": "OSError",
    "stackTrace": [
        "  File \"/var/lang/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
        "  File \"/var/lang/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
        "  File \"<frozen importlib._bootstrap>\", line 696, in _load\n",
        "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
        "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
        "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
        "  File \"/var/task/handler.py\", line 23, in <module>\n    nlp = spacy.load('en_core_web_sm')\n",
        "  File \"/opt/python/spacy/__init__.py\", line 30, in load\n    return util.load_model(name, **overrides)\n",
        "  File \"/opt/python/spacy/util.py\", line 169, in load_model\n    raise IOError(Errors.E050.format(name=name))\n"
    ]
}

**Screenshots**

**Layer Version ARN:**
Specific Layer ARN that didn't work (let's us know which version, region etc).
  - arn:aws:lambda:ap-southeast-1:113088814899:layer:Klayers-python37-spacy:9

**Framework:**
What Framework do you use (Serverless, Architect, Zappa, or just Console?)
Serverless

**Additional context**

I am using it as below:

import spacy
nlp = spacy.load('en_core_web_sm')

**Comment by keithrozario** [comment] 2020-01-07 04:53
This looks like a duplicate of https://github.com/keithrozario/Klayers/issues/77

You need to upload your own language files for spaCy. Refer to the link above for help.

**Closed** 2020-01-13 22:39 UTC
